### ISSUE TITLE
I can't browserhax my PC

### ISSUE THREAD

**Issue by ghost** [zoogie/old-browserhax#1]
Zoogig pls fix I can't browerhax my pc please fix so I can pi.. I mean uhh play out of region games and get user made themes and play kick ass homebrew:tm: please fix please please please please please please please please PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE fix :)

**Comment by zoogie** [comment]
WHAT IS WRONG WITH THE ELF :p

**Comment by ThatNerdyPikachu** [comment]
@zoogie: Where is that from? It's seemingly from all(?) of your projects, and I'm curious the origins of this m a g i c a l  string.

**Comment by zoogie** [comment]
@ThatNerdyPikachu  Pokemon Vietnam Crystal. It's a bootleg of the game with a hilariously bad translation.

A sample:
https://twitter.com/vietnamcrystal?lang=en

Not the first time used in 3ds homebrew either:
https://github.com/MrCheeze/GYTB/blob/master/source/main.c#L534
